[package]
name = "sumcheck"
version.workspace = true
edition.workspace = true

[features]
default = []
gpu = []

[lints]
workspace = true

[dependencies]
p3-field.workspace = true
tracing.workspace = true
utils.workspace = true
rayon.workspace = true
p3-air.workspace = true
p3-matrix.workspace = true
p3-challenger.workspace = true
whir-p3.workspace = true
smallvec = "1.13.2"

[dev-dependencies]
p3-koala-bear.workspace = true
rand.workspace = true
